 ' UCF COP3330 Fall 2021 Assignment 3 Solution
 ' Copyright 2021 James Karlinski

@startuml
class ex44.Product
{
    + String name
    + int quantity
    + double price
}

class ex44.ProductManager
{
    - {static} String PRODUCTS
    - {static} String NAME
    - {static} String PRICE
    - {static} String QUANTITY
    - {static} Scanner scanner

    - List<Product> products

    - String getInput(String)
    - JsonElement getValue(JsonElement,String)
    - void setProductsListFromJsonData(String)

    + Product findProduct(String)
    + void output(String)
    + String takeSearchInputAndSearch()
}
@enduml