' UCF COP3330 Fall 2021 Assignment 3 Solution
' Copyright 2021 James Karlinski

@startuml
class ex41.FileManager
{
    + ArrayList<String> getPeopleListFromFile()
    + void writePeopleListToOutputFile(ArrayList<String>)

    - {static} String INPUT_FILE_NAME
    - {static} String OUTPUT_FILE_NAME

    - File createOutputFile()
    - void sortPeopleList(ArrayList<String>)
    - void output(String)
}
@enduml
