' UCF COP3330 Fall 2021 Assignment 3 Solution
' Copyright 2021 James Karlinski

@startuml
class ex42.FileParser
{
    + ArrayList<String> getLinesFromInputFile()
    + void output(String)
    + String parseTable(ArrayList<String>)

    - {static} String _inputFilePath
    - String parseRawLine(String)
}
@enduml