' UCF COP3330 Fall 2021 Assignment 3 Solution
' Copyright 2021 James Karlinski

@startuml
class ex43.WebsiteDetails
{
    - {static} String ROOT_PATH

    + boolean createJsFolder
    + boolean createCssFolder
    + String authorName
    + String htmlTemplate
    + String siteName
    + String websiteDirPath
}

class ex43.WebsiteBuilder
{
    - {static} Scanner scanner
    - {static} String INDEX_FILE_NAME
    - {static} String JS_FOLDER_NAME
    - {static} String CSS_FOLDER_NAME

    + void createWebsite(WebsiteDetails)
    + void output(String,boolean)
    + String getInput(String)
}
@enduml